@API_HostAddress = http://localhost:5282

// HTTP GET запрос для получения информации о препорате.
GET {{API_HostAddress}}/weatherforecast/ 
Accept: application/json  // Указывает, что ответ должен быть в формате JSON.

###
